development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: centralize_app_store_development
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: centralize_app_store_production
  pool: 5
  username: root
  password: root
  host: db